apiVersion: v1
kind: Pod
metadata:
  name: my-pod
  namespace: ns-1
spec:
  containers:
  - name: my-container
    image: urajes123/testgitlab:latest
    imagePullPolicy: IfNotPresent
  imagePullSecrets:
    - name: regcred
